# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 手动任务-壁纸批量下载

on:
  workflow_dispatch:
    inputs:
      fromDate:
        description: '下载起始时间'
        required: true
        type: date
      toDate:
        description: '下载结束时间'
        required: true
        type: date

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Java Application
        run: java -jar target/image-save-jar-with-dependencies.jar ${{ github.event.inputs.fromDate }} ${{ github.event.inputs.toDate }}
      - name: Upload Release # 发布到 Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # 因为之前已经创建了 Release，所以要进行更新
          omitName: true # 更新的时候不改变 Release 的名字
          artifacts: 'downs.zip' # 多个文件逗号分开
          token: ${{ secrets.MY_GIT_TOKEN }} # https://github.com/settings/tokens 只选 repo 就行
