# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Image Save with Maven

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/image-save-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "wefashe@qq.com"
         git config --local user.name "wefashe"
         git pull
         git add README.md
         git add images/*
         git commit -m "update readme.md"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
