# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 早上2点定时保存壁纸

on:
  schedule:
    # UTC时间与北京时间8小时时差
    # UTC时间 18点执行一次，即UTC+8北京时间 2点执行一次
    - cron:  '0 18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/image-save-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "wefashe@qq.com"
         git config --local user.name "Java CI"
         git pull
         git add .
         git commit -m "$(git config user.name) Auto Save Wallpaper At `date +%Y-%m-%d\ %H:%M:%S`"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
